export interface SkillMeta {
  name: string;
  displayName: string;
  description: string;
  tools: string[];
  theme: string;
  githubUrl?: string;
  requires?: string[];
}

export interface Theme {
  slug: string;
  name: string;
  description: string;
  skills: SkillMeta[];
}

export const THEMES: Theme[] = [
  {
    slug: "amazon",
    name: "Amazon Selling",
    description: "Amazon FBA, keyword research, PPC, listing optimization, and profit calculation.",
    skills: [
      {
        name: "amazon_skills",
        displayName: "Amazon Skills",
        description: "Complete Amazon toolkit: FBA fee calculation, keyword research, listing optimization, PPC campaigns, sales estimation, and tariff calculation.",
        tools: ["list_amazon_skills", "get_amazon_skill", "calculate_fba_fees"],
        theme: "amazon",
        githubUrl: "https://github.com/nexscope-ai/Amazon-Skills",
      },
    ],
  },
  {
    slug: "marketing",
    name: "Marketing",
    description: "Conversion copywriting, content strategy, email, paid ads, SEO, and growth.",
    skills: [
      {
        name: "marketing_skills",
        displayName: "Marketing Skills",
        description: "Complete marketing toolkit: copywriting, email sequences, cold outreach, paid ads, launch strategy, CRO, pricing strategy, and analytics tracking.",
        tools: ["list_marketing_skills", "get_marketing_skill", "get_marketing_workflow"],
        theme: "marketing",
        githubUrl: "https://github.com/coreyhaines31/marketingskills",
      },
    ],
  },
  {
    slug: "seo",
    name: "SEO & Search",
    description: "Keyword research, on-page SEO, technical SEO, link building, and geo-targeting.",
    skills: [
      {
        name: "seo_geo",
        displayName: "SEO & GEO Skills",
        description: "Complete SEO toolkit: keyword research, technical audits, on-page optimization, backlink analysis, rank tracking, schema markup, content writing, and geo-targeted content for AI search.",
        tools: ["list_seo_skills", "get_seo_skill", "get_seo_workflow"],
        theme: "seo",
        githubUrl: "https://github.com/aaron-he-zhu/seo-geo-claude-skills",
      },
    ],
  },
  {
    slug: "ecommerce",
    name: "E-Commerce",
    description: "Shopify, Amazon, Etsy, TikTok Shop: listings, ads, pricing, and operations.",
    skills: [
      {
        name: "ecommerce_skills",
        displayName: "E-Commerce Skills",
        description: "E-commerce toolkit: profit calculators, competitor pricing, CRO, keyword research, email marketing, Etsy SEO, Google Shopping ads, inventory management, and product research.",
        tools: ["list_ecommerce_skills", "get_ecommerce_skill", "get_ecommerce_workflow"],
        theme: "ecommerce",
        githubUrl: "https://github.com/nexscope-ai/eCommerce-Skills",
      },
    ],
  },
  {
    slug: "agency_agents",
    name: "Agency Agents",
    description: "144+ AI agent personas across 12 professional divisions.",
    skills: [
      {
        name: "agency_agents",
        displayName: "Agency Agents",
        description: "144+ AI agent personas across 12 professional divisions: academic, design, engineering, finance, game development, marketing, product, project management, sales, support, and testing.",
        tools: ["list_agents", "get_agent_persona", "search_agents"],
        theme: "agency_agents",
        githubUrl: "https://github.com/msitarzewski/agency-agents",
      },
    ],
  },
  {
    slug: "_unthemed",
    name: "Uncategorized",
    description: "Skills not yet assigned to a theme.",
    skills: [
      {
        name: "video_downloader",
        displayName: "Video Downloader",
        description: "",
        tools: ["list_video_downloader_skills", "get_video_downloader_skill"],
        theme: "_unthemed",
      },
      {
        name: "theme_factory",
        displayName: "Theme Factory",
        description: "",
        tools: ["list_theme_factory_skills", "get_theme_factory_skill"],
        theme: "_unthemed",
      },
      {
        name: "template_skill",
        displayName: "Template Skill",
        description: "",
        tools: ["list_template_skill_skills", "get_template_skill_skill"],
        theme: "_unthemed",
      },
      {
        name: "raffle_winner_picker",
        displayName: "Raffle Winner Picker",
        description: "",
        tools: ["list_raffle_winner_picker_skills", "get_raffle_winner_picker_skill"],
        theme: "_unthemed",
      },
      {
        name: "property_staging_skill",
        displayName: "Property Staging Skill",
        description: "",
        tools: ["get_guidance"],
        theme: "_unthemed",
      },
      {
        name: "project_manager_skill",
        displayName: "Project Manager Skill",
        description: "",
        tools: ["list_project_manager_skill_skills", "get_project_manager_skill_skill"],
        theme: "_unthemed",
      },
      {
        name: "pixelle_video",
        displayName: "Pixelle Video",
        description: "",
        tools: ["list_pixelle_video_skills", "get_pixelle_video_skill"],
        theme: "_unthemed",
      },
      {
        name: "notion_research_documentation",
        displayName: "Notion Research Documentation",
        description: "",
        tools: ["list_notion_research_documentation_skills", "get_notion_research_documentation_skill"],
        theme: "_unthemed",
      },
      {
        name: "notion_meeting_intelligence",
        displayName: "Notion Meeting Intelligence",
        description: "",
        tools: ["list_notion_meeting_intelligence_skills", "get_notion_meeting_intelligence_skill"],
        theme: "_unthemed",
      },
      {
        name: "notebooklm_skill",
        displayName: "NotebookLM Skill",
        description: "Let Claude Code query your NotebookLM notebooks directly — get source-grounded answers from your documents without copy-pasting.",
        tools: ["list_notebooklm_skill_skills", "get_notebooklm_skill_skill"],
        theme: "_unthemed",
        githubUrl: "https://github.com/PleasePrompto/notebooklm-skill",
      },
      {
        name: "meeting_insights_analyzer",
        displayName: "Meeting Insights Analyzer",
        description: "",
        tools: ["list_meeting_insights_analyzer_skills", "get_meeting_insights_analyzer_skill"],
        theme: "_unthemed",
      },
      {
        name: "mcp_builder",
        displayName: "Mcp Builder",
        description: "",
        tools: ["list_mcp_builder_skills", "get_mcp_builder_skill"],
        theme: "_unthemed",
      },
      {
        name: "domain_name_brainstormer",
        displayName: "Domain Name Brainstormer",
        description: "",
        tools: ["list_domain_name_brainstormer_skills", "get_domain_name_brainstormer_skill"],
        theme: "_unthemed",
      },
      {
        name: "capabilities",
        displayName: "Capabilities",
        description: "",
        tools: ["get_guidance"],
        theme: "_unthemed",
      },
      {
        name: "canvas_design",
        displayName: "Canvas Design",
        description: "",
        tools: ["list_canvas_design_skills", "get_canvas_design_skill"],
        theme: "_unthemed",
      },
      {
        name: "algorithmic_art",
        displayName: "Algorithmic Art",
        description: "",
        tools: ["list_algorithmic_art_skills", "get_algorithmic_art_skill"],
        theme: "_unthemed",
      },
      {
        name: "rednote_bootstrap",
        displayName: "Rednote Bootstrap",
        description: "",
        tools: ["list_rednote_bootstrap_skills", "get_rednote_bootstrap_skill"],
        theme: "_unthemed",
      },
      {
        name: "skill_creator",
        displayName: "Skill Creator",
        description: "",
        tools: ["list_skill_creator_skills", "get_skill_creator_skill"],
        theme: "_unthemed",
      },
      {
        name: "content_research_writer",
        displayName: "Content Research Writer",
        description: "",
        tools: ["list_content_research_writer_skills", "get_content_research_writer_skill"],
        theme: "_unthemed",
      },
      {
        name: "contributing",
        displayName: "Contributing",
        description: "",
        tools: ["get_guidance"],
        theme: "_unthemed",
      },
      {
        name: "file_organizer",
        displayName: "File Organizer",
        description: "",
        tools: ["list_file_organizer_skills", "get_file_organizer_skill"],
        theme: "_unthemed",
      },
      {
        name: "gstack",
        displayName: "Gstack",
        description: "",
        tools: ["list_gstack_skills", "get_gstack_skill"],
        theme: "_unthemed",
      },
      {
        name: "tvc_director",
        displayName: "Tvc Director",
        description: "",
        tools: ["list_tvc_director_skills", "get_tvc_director_skill"],
        theme: "_unthemed",
      },
      {
        name: "slack_gif_creator",
        displayName: "Slack Gif Creator",
        description: "",
        tools: ["list_slack_gif_creator_skills", "get_slack_gif_creator_skill"],
        theme: "_unthemed",
      },
      {
        name: "resemble_detect",
        displayName: "Resemble Detect",
        description: "",
        tools: ["list_resemble_detect_skills", "get_resemble_detect_skill"],
        theme: "_unthemed",
      },
      {
        name: "notion_spec_to_implementation",
        displayName: "Notion Spec To Implementation",
        description: "",
        tools: ["list_notion_spec_to_implementation_skills", "get_notion_spec_to_implementation_skill"],
        theme: "_unthemed",
      },
      {
        name: "changelog_generator",
        displayName: "Changelog Generator",
        description: "",
        tools: ["list_changelog_generator_skills", "get_changelog_generator_skill"],
        theme: "_unthemed",
      },
      {
        name: "colleague_skill",
        displayName: "Colleague Skill",
        description: "",
        tools: ["build_colleague_skill", "get_colleague_intake_questions"],
        theme: "_unthemed",
      },
      {
        name: "feedback_skill",
        displayName: "Feedback Skill",
        description: "",
        tools: ["submit_feedback"],
        theme: "_unthemed",
      },
      {
        name: "minto_content_writing",
        displayName: "Minto Content Writing",
        description: "",
        tools: ["list_minto_content_writing_skills", "get_minto_content_writing_skill"],
        theme: "_unthemed",
      },
      {
        name: "notebooklm_py",
        displayName: "Notebooklm Py",
        description: "",
        tools: ["list_notebooklm_py_skills", "get_notebooklm_py_skill"],
        theme: "_unthemed",
      },
      {
        name: "architecture",
        displayName: "Architecture",
        description: "",
        tools: ["get_guidance"],
        theme: "_unthemed",
      },
      {
        name: "artifacts_builder",
        displayName: "Artifacts Builder",
        description: "",
        tools: ["list_artifacts_builder_skills", "get_artifacts_builder_skill"],
        theme: "_unthemed",
      },
      {
        name: "brand_guidelines",
        displayName: "Brand Guidelines",
        description: "",
        tools: ["list_brand_guidelines_skills", "get_brand_guidelines_skill"],
        theme: "_unthemed",
      },
      {
        name: "competitive_ads_extractor",
        displayName: "Competitive Ads Extractor",
        description: "",
        tools: ["list_competitive_ads_extractor_skills", "get_competitive_ads_extractor_skill"],
        theme: "_unthemed",
      },
      {
        name: "graphify",
        displayName: "Graphify",
        description: "",
        tools: ["list_graphify_skills", "get_graphify_skill"],
        theme: "_unthemed",
      },
      {
        name: "image_enhancer",
        displayName: "Image Enhancer",
        description: "",
        tools: ["list_image_enhancer_skills", "get_image_enhancer_skill"],
        theme: "_unthemed",
      },
      {
        name: "internal_comms",
        displayName: "Internal Comms",
        description: "",
        tools: ["list_internal_comms_skills", "get_internal_comms_skill"],
        theme: "_unthemed",
      },
      {
        name: "invoice_organizer",
        displayName: "Invoice Organizer",
        description: "",
        tools: ["list_invoice_organizer_skills", "get_invoice_organizer_skill"],
        theme: "_unthemed",
      },
      {
        name: "lead_research_assistant",
        displayName: "Lead Research Assistant",
        description: "",
        tools: ["list_lead_research_assistant_skills", "get_lead_research_assistant_skill"],
        theme: "_unthemed",
      },
      {
        name: "notion_knowledge_capture",
        displayName: "Notion Knowledge Capture",
        description: "",
        tools: ["list_notion_knowledge_capture_skills", "get_notion_knowledge_capture_skill"],
        theme: "_unthemed",
      },
      {
        name: "webapp_testing",
        displayName: "Webapp Testing",
        description: "",
        tools: ["list_webapp_testing_skills", "get_webapp_testing_skill"],
        theme: "_unthemed",
      },
      {
        name: "service_bridge",
        displayName: "Service Bridge",
        description: "Query your connected services (Supabase, GitHub, Notion, OpenAI, custom APIs) directly from chat using stored credentials.",
        tools: ["get_service_bridge_guidance", "list_connected_services", "describe_service_schema", "query_connected_service"],
        theme: "_unthemed",
      },
      {
        name: "industry_expert",
        displayName: "Industry Expert",
        description: "",
        tools: ["list_industry_expert_skills", "get_industry_expert_skill"],
        theme: "_unthemed",
      },
      {
        name: "industry_master",
        displayName: "Industry Master",
        description: "",
        tools: ["list_industry_master_skills", "get_industry_master_skill"],
        theme: "_unthemed",
      },
    ],
  },
  {
    slug: "engineering",
    name: "Engineering",
    description: "",
    skills: [
      {
        name: "voltagent_voltagent_skills",
        displayName: "Voltagent Voltagent Skills",
        description: "",
        tools: ["list_voltagent_voltagent_skills_skills", "get_voltagent_voltagent_skills_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/VoltAgent/skills",
      },
      {
        name: "vercel_skills",
        displayName: "Vercel Skills",
        description: "",
        tools: ["list_vercel_skills_skills", "get_vercel_skills_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/vercel-labs/agent-skills",
      },
      {
        name: "superpowers",
        displayName: "Superpowers",
        description: "",
        tools: ["list_superpowers_skills", "get_superpowers_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/obra/superpowers",
      },
      {
        name: "qdrant_skills",
        displayName: "Qdrant Skills",
        description: "",
        tools: ["list_qdrant_skills_skills", "get_qdrant_skills_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/qdrant/mcp-server-qdrant",
      },
      {
        name: "microsoft_azure",
        displayName: "Microsoft Azure",
        description: "",
        tools: ["list_microsoft_azure_skills", "get_microsoft_azure_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/microsoft/skills",
      },
      {
        name: "google_gemini_skills",
        displayName: "Google Gemini Skills",
        description: "",
        tools: ["list_google_gemini_skills_skills", "get_google_gemini_skills_skill"],
        theme: "engineering",
      },
      {
        name: "anthropic_cybersecurity_skills",
        displayName: "Anthropic Cybersecurity Skills",
        description: "",
        tools: ["list_anthropic_cybersecurity_skills_skills", "get_anthropic_cybersecurity_skills_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/mukul975/Anthropic-Cybersecurity-Skills",
      },
      {
        name: "ai_coding_skills",
        displayName: "Ai Coding Skills",
        description: "",
        tools: ["list_ai_coding_skills_skills", "get_ai_coding_skills_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/sanjay3290/ai-skills",
      },
      {
        name: "google_agent_skills",
        displayName: "Google Agent Skills",
        description: "",
        tools: ["list_google_agent_skills_skills", "get_google_agent_skills_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/google/skills",
      },
      {
        name: "composiohq",
        displayName: "Composiohq",
        description: "",
        tools: ["list_composiohq_skills", "get_composiohq_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/ComposioHQ/skills",
      },
      {
        name: "better_auth",
        displayName: "Better Auth",
        description: "",
        tools: ["list_better_auth_skills", "get_better_auth_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/better-auth/skills",
      },
      {
        name: "tinybird",
        displayName: "Tinybird",
        description: "",
        tools: ["list_tinybird_skills", "get_tinybird_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/tinybirdco/tinybird-agent-skills",
      },
      {
        name: "agent_toolkit",
        displayName: "Agent Toolkit",
        description: "",
        tools: ["list_agent_toolkit_skills", "get_agent_toolkit_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/sanity-io/agent-toolkit",
      },
      {
        name: "linear_claude_skill",
        displayName: "Linear Claude Skill",
        description: "",
        tools: ["list_linear_claude_skill_skills", "get_linear_claude_skill_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/wrsmith108/linear-claude-skill",
      },
      {
        name: "claude_speed_reader",
        displayName: "Claude Speed Reader",
        description: "",
        tools: ["list_claude_speed_reader_skills", "get_claude_speed_reader_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/SeanZoR/claude-speed-reader",
      },
      {
        name: "common_tasks_agent_skills",
        displayName: "Common Tasks Agent Skills",
        description: "",
        tools: ["list_common_tasks_agent_skills_skills", "get_common_tasks_agent_skills_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/Shpigford/skills",
      },
      {
        name: "aws_skills",
        displayName: "Aws Skills",
        description: "",
        tools: ["list_aws_skills_skills", "get_aws_skills_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/zxkane/aws-skills",
      },
      {
        name: "claude_bootstrap",
        displayName: "Claude Bootstrap",
        description: "",
        tools: ["list_claude_bootstrap_skills", "get_claude_bootstrap_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/alinaqi/claude-bootstrap",
      },
      {
        name: "recursive_decomposition_skill",
        displayName: "Recursive Decomposition Skill",
        description: "",
        tools: ["list_recursive_decomposition_skill_skills", "get_recursive_decomposition_skill_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/massimodeluisa/recursive-decomposition-skill",
      },
      {
        name: "claude_code_startup",
        displayName: "Claude Code Startup",
        description: "",
        tools: ["list_claude_code_startup_skills", "get_claude_code_startup_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/rameerez/claude-code-startup-skills",
      },
      {
        name: "model_hierarchy_skill",
        displayName: "Model Hierarchy Skill",
        description: "",
        tools: ["list_model_hierarchy_skill_skills", "get_model_hierarchy_skill_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/zscole/model-hierarchy-skill",
      },
      {
        name: "varlock_claude_skill",
        displayName: "Varlock Claude Skill",
        description: "",
        tools: ["list_varlock_claude_skill_skills", "get_varlock_claude_skill_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/wrsmith108/varlock-claude-skill",
      },
      {
        name: "codex_collab",
        displayName: "Codex Collab",
        description: "",
        tools: ["list_codex_collab_skills", "get_codex_collab_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/Kevin7Qi/codex-collab",
      },
      {
        name: "nodejs_skill",
        displayName: "Nodejs Skill",
        description: "",
        tools: ["list_nodejs_skill_skills", "get_nodejs_skill_skill"],
        theme: "engineering",
        githubUrl: "https://github.com/mcollina/skills",
      },
    ],
  },
  {
    slug: "data_analysis",
    name: "Data Analysis",
    description: "",
    skills: [
      {
        name: "clickhouse_skills",
        displayName: "Clickhouse Skills",
        description: "",
        tools: ["list_clickhouse_skills_skills", "get_clickhouse_skills_skill"],
        theme: "data_analysis",
        githubUrl: "https://github.com/ClickHouse/clickhousectl",
      },
    ],
  },
  {
    slug: "database",
    name: "Database",
    description: "",
    skills: [
      {
        name: "supabase_supabase_agent_skills",
        displayName: "Supabase Supabase Agent Skills",
        description: "",
        tools: ["list_supabase_supabase_agent_skills_skills", "get_supabase_supabase_agent_skills_skill"],
        theme: "database",
      },
      {
        name: "mongodb_skills",
        displayName: "Mongodb Skills",
        description: "",
        tools: ["list_mongodb_skills_skills", "get_mongodb_skills_skill"],
        theme: "database",
        githubUrl: "https://github.com/mongodb/agent-skills",
      },
      {
        name: "duckdb_skills",
        displayName: "Duckdb Skills",
        description: "",
        tools: ["list_duckdb_skills_skills", "get_duckdb_skills_skill"],
        theme: "database",
        githubUrl: "https://github.com/duckdb/duckdb-skills",
      },
      {
        name: "neondatabase",
        displayName: "Neondatabase",
        description: "",
        tools: ["list_neondatabase_skills", "get_neondatabase_skill"],
        theme: "database",
        githubUrl: "https://github.com/neondatabase/agent-skills",
      },
      {
        name: "data_structure_protocol",
        displayName: "Data Structure Protocol",
        description: "",
        tools: ["list_data_structure_protocol_skills", "get_data_structure_protocol_skill"],
        theme: "database",
        githubUrl: "https://github.com/k-kolomeitsev/data-structure-protocol",
      },
    ],
  },
  {
    slug: "product_management",
    name: "Product Management",
    description: "",
    skills: [
      {
        name: "phuryn_pm_skills",
        displayName: "Phuryn Pm Skills",
        description: "",
        tools: ["list_phuryn_pm_skills_skills", "get_phuryn_pm_skills_skill"],
        theme: "product_management",
      },
    ],
  },
  {
    slug: "productibility",
    name: "Productibility",
    description: "",
    skills: [
      {
        name: "resend_skills",
        displayName: "Resend Skills",
        description: "",
        tools: ["list_resend_skills_skills", "get_resend_skills_skill"],
        theme: "productibility",
        githubUrl: "https://github.com/resend/resend-cli",
      },
    ],
  },
  {
    slug: "payment",
    name: "Payment",
    description: "",
    skills: [
      {
        name: "stripe_stripe_skills",
        displayName: "Stripe Stripe Skills",
        description: "",
        tools: ["list_stripe_stripe_skills_skills", "get_stripe_stripe_skills_skill"],
        theme: "payment",
      },
    ],
  },
  {
    slug: "design",
    name: "Design",
    description: "",
    skills: [
      {
        name: "figma",
        displayName: "Figma",
        description: "",
        tools: ["list_figma_skills", "get_figma_skill"],
        theme: "design",
        githubUrl: "https://github.com/figma/mcp-server-guide",
      },
    ],
  },
  {
    slug: "llm_official_skill",
    name: "Llm Official Skill",
    description: "",
    skills: [
      {
        name: "openai",
        displayName: "Openai",
        description: "",
        tools: ["list_openai_skills", "get_openai_skill"],
        theme: "llm_official_skill",
        githubUrl: "https://github.com/openai/skills",
      },
    ],
  },
  {
    slug: "wordpress",
    name: "Wordpress",
    description: "",
    skills: [
      {
        name: "wordpress",
        displayName: "Wordpress",
        description: "",
        tools: ["list_wordpress_skills", "get_wordpress_skill"],
        theme: "wordpress",
        githubUrl: "https://github.com/WordPress/agent-skills",
      },
    ],
  },
  {
    slug: "huggingface",
    name: "Huggingface",
    description: "",
    skills: [
      {
        name: "huggingface",
        displayName: "Huggingface",
        description: "",
        tools: ["list_huggingface_skills", "get_huggingface_skill"],
        theme: "huggingface",
        githubUrl: "https://github.com/huggingface/skills",
      },
    ],
  },
  {
    slug: "web_search",
    name: "Web Search",
    description: "",
    skills: [
      {
        name: "brave",
        displayName: "Brave",
        description: "",
        tools: ["list_brave_skills", "get_brave_skill"],
        theme: "web_search",
        githubUrl: "https://github.com/brave/brave-search-skills",
      },
    ],
  },
  {
    slug: "crypto",
    name: "Crypto",
    description: "",
    skills: [
      {
        name: "coinbase",
        displayName: "Coinbase",
        description: "",
        tools: ["list_coinbase_skills", "get_coinbase_skill"],
        theme: "crypto",
        githubUrl: "https://github.com/coinbase/agentic-wallet-skills",
      },
    ],
  },
  {
    slug: "firebase",
    name: "Firebase",
    description: "",
    skills: [
      {
        name: "firebase",
        displayName: "Firebase",
        description: "",
        tools: ["list_firebase_skills", "get_firebase_skill"],
        theme: "firebase",
        githubUrl: "https://github.com/firebase/agent-skills",
      },
    ],
  },
  {
    slug: "productivity",
    name: "Productivity",
    description: "",
    skills: [
      {
        name: "notion",
        displayName: "Notion",
        description: "",
        tools: ["list_notion_skills", "get_notion_skill"],
        theme: "productivity",
        githubUrl: "https://github.com/makenotion/notion-cookbook",
      },
      {
        name: "superpowers_lab",
        displayName: "Superpowers Lab",
        description: "",
        tools: ["list_superpowers_lab_skills", "get_superpowers_lab_skill"],
        theme: "productivity",
        githubUrl: "https://github.com/obra/superpowers-lab",
      },
      {
        name: "shpigford",
        displayName: "Shpigford",
        description: "",
        tools: ["list_shpigford_skills", "get_shpigford_skill"],
        theme: "productivity",
        githubUrl: "https://github.com/Shpigford/skills",
      },
      {
        name: "translate_book",
        displayName: "Translate Book",
        description: "",
        tools: ["list_translate_book_skills", "get_translate_book_skill"],
        theme: "productivity",
        githubUrl: "https://github.com/deusyu/translate-book",
      },
      {
        name: "skill_seekers",
        displayName: "Skill Seekers",
        description: "",
        tools: ["list_skill_seekers_skills", "get_skill_seekers_skill"],
        theme: "productivity",
        githubUrl: "https://github.com/yusufkaraaslan/Skill_Seekers",
      },
      {
        name: "understand_anything",
        displayName: "Understand Anything",
        description: "",
        tools: ["list_understand_anything_skills", "get_understand_anything_skill"],
        theme: "productivity",
        githubUrl: "https://github.com/Lum1104/Understand-Anything",
      },
      {
        name: "skill_optimizer",
        displayName: "Skill Optimizer",
        description: "",
        tools: ["list_skill_optimizer_skills", "get_skill_optimizer_skill"],
        theme: "productivity",
        githubUrl: "https://github.com/hqhq1025/skill-optimizer",
      },
      {
        name: "claude_apple_bridges",
        displayName: "Claude Apple Bridges",
        description: "",
        tools: ["list_claude_apple_bridges_skills", "get_claude_apple_bridges_skill"],
        theme: "productivity",
        githubUrl: "https://github.com/more-io/claude-apple-bridges",
      },
      {
        name: "kicad_happy",
        displayName: "Kicad Happy",
        description: "",
        tools: ["list_kicad_happy_skills", "get_kicad_happy_skill"],
        theme: "productivity",
        githubUrl: "https://github.com/aklofas/kicad-happy",
      },
    ],
  },
  {
    slug: "web_dev",
    name: "Web Dev",
    description: "",
    skills: [
      {
        name: "web_quality",
        displayName: "Web Quality",
        description: "",
        tools: ["list_web_quality_skills", "get_web_quality_skill"],
        theme: "web_dev",
        githubUrl: "https://github.com/addyosmani/web-quality-skills",
      },
    ],
  },
  {
    slug: "digital_marketing",
    name: "Digital Marketing",
    description: "",
    skills: [
      {
        name: "ai_marketing",
        displayName: "Ai Marketing",
        description: "",
        tools: ["list_ai_marketing_skills", "get_ai_marketing_skill"],
        theme: "digital_marketing",
        githubUrl: "https://github.com/BrianRWagner/ai-marketing-claude-code-skills",
      },
    ],
  },
  {
    slug: "content_visibility",
    name: "Content Visibility",
    description: "",
    skills: [
      {
        name: "claude_seo",
        displayName: "Claude Seo",
        description: "",
        tools: ["list_claude_seo_skills", "get_claude_seo_skill"],
        theme: "content_visibility",
        githubUrl: "https://github.com/AgriciDaniel/claude-seo",
      },
      {
        name: "aso_skills",
        displayName: "Aso Skills",
        description: "",
        tools: ["list_aso_skills_skills", "get_aso_skills_skill"],
        theme: "content_visibility",
        githubUrl: "https://github.com/Eronred/aso-skills",
      },
    ],
  },
  {
    slug: "content_management",
    name: "Content Management",
    description: "",
    skills: [
      {
        name: "x_article_publisher_skill",
        displayName: "X Article Publisher Skill",
        description: "",
        tools: ["list_x_article_publisher_skill_skills", "get_x_article_publisher_skill_skill"],
        theme: "content_management",
        githubUrl: "https://github.com/wshuyi/x-article-publisher-skill",
      },
      {
        name: "tweetclaw",
        displayName: "Tweetclaw",
        description: "",
        tools: ["list_tweetclaw_skills", "get_tweetclaw_skill"],
        theme: "content_management",
        githubUrl: "https://github.com/Xquik-dev/tweetclaw",
      },
    ],
  },
  {
    slug: "email_marketing",
    name: "Email Marketing",
    description: "",
    skills: [
      {
        name: "email_marketing_bible",
        displayName: "Email Marketing Bible",
        description: "",
        tools: ["list_email_marketing_bible_skills", "get_email_marketing_bible_skill"],
        theme: "email_marketing",
        githubUrl: "https://github.com/CosmoBlk/email-marketing-bible",
      },
    ],
  },
  {
    slug: "content_creation",
    name: "Content Creation",
    description: "",
    skills: [
      {
        name: "creative_director_skill",
        displayName: "Creative Director Skill",
        description: "",
        tools: ["list_creative_director_skill_skills", "get_creative_director_skill_skill"],
        theme: "content_creation",
        githubUrl: "https://github.com/smixs/creative-director-skill",
      },
      {
        name: "humanizer",
        displayName: "Humanizer",
        description: "",
        tools: ["list_humanizer_skills", "get_humanizer_skill"],
        theme: "content_creation",
        githubUrl: "https://github.com/blader/humanizer",
      },
      {
        name: "wonda",
        displayName: "Wonda",
        description: "",
        tools: ["list_wonda_skills", "get_wonda_skill"],
        theme: "content_creation",
        githubUrl: "https://github.com/degausai/wonda",
      },
      {
        name: "youtube_clipper",
        displayName: "Youtube Clipper",
        description: "",
        tools: ["list_youtube_clipper_skills", "get_youtube_clipper_skill"],
        theme: "content_creation",
        githubUrl: "https://github.com/op7418/Youtube-clipper-skill",
      },
      {
        name: "video_db_skills",
        displayName: "Video Db Skills",
        description: "",
        tools: ["list_video_db_skills_skills", "get_video_db_skills_skill"],
        theme: "content_creation",
        githubUrl: "https://github.com/video-db/skills",
      },
    ],
  },
  {
    slug: "engineering_frontend_development",
    name: "Engineering Frontend Development",
    description: "",
    skills: [
      {
        name: "frontend_slides",
        displayName: "Frontend Slides",
        description: "",
        tools: ["list_frontend_slides_skills", "get_frontend_slides_skill"],
        theme: "engineering_frontend_development",
        githubUrl: "https://github.com/zarazhangrui/frontend-slides",
      },
      {
        name: "ui_skills",
        displayName: "Ui Skills",
        description: "",
        tools: ["list_ui_skills_skills", "get_ui_skills_skill"],
        theme: "engineering_frontend_development",
        githubUrl: "https://github.com/ibelick/ui-skills",
      },
      {
        name: "ui_ux_pro_max",
        displayName: "Ui Ux Pro Max",
        description: "",
        tools: ["list_ui_ux_pro_max_skills", "get_ui_ux_pro_max_skill"],
        theme: "engineering_frontend_development",
        githubUrl: "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill",
      },
      {
        name: "swiftui_agent_skill",
        displayName: "Swiftui Agent Skill",
        description: "",
        tools: ["list_swiftui_agent_skill_skills", "get_swiftui_agent_skill_skill"],
        theme: "engineering_frontend_development",
        githubUrl: "https://github.com/AvdLee/SwiftUI-Agent-Skill",
      },
      {
        name: "swift_patterns",
        displayName: "Swift Patterns",
        description: "",
        tools: ["list_swift_patterns_skills", "get_swift_patterns_skill"],
        theme: "engineering_frontend_development",
        githubUrl: "https://github.com/efremidze/swift-patterns-skill",
      },
      {
        name: "taste_skill",
        displayName: "Taste Skill",
        description: "",
        tools: ["list_taste_skill_skills", "get_taste_skill_skill"],
        theme: "engineering_frontend_development",
        githubUrl: "https://github.com/Leonxlnx/taste-skill",
      },
    ],
  },
  {
    slug: "operations",
    name: "Operations",
    description: "",
    skills: [
      {
        name: "founder_skills",
        displayName: "Founder Skills",
        description: "",
        tools: ["list_founder_skills_skills", "get_founder_skills_skill"],
        theme: "operations",
        githubUrl: "https://github.com/ognjengt/founder-skills",
      },
      {
        name: "charlie_cfo_skill",
        displayName: "Charlie Cfo Skill",
        description: "",
        tools: ["list_charlie_cfo_skill_skills", "get_charlie_cfo_skill_skill"],
        theme: "operations",
        githubUrl: "https://github.com/EveryInc/charlie-cfo-skill",
      },
      {
        name: "opc_skills",
        displayName: "Opc Skills",
        description: "",
        tools: ["list_opc_skills_skills", "get_opc_skills_skill"],
        theme: "operations",
        githubUrl: "https://github.com/ReScienceLab/opc-skills",
      },
    ],
  },
  {
    slug: "engineering_context_eng",
    name: "Engineering Context Eng",
    description: "",
    skills: [
      {
        name: "claude_memory",
        displayName: "Claude Memory",
        description: "",
        tools: ["list_claude_memory_skills", "get_claude_memory_skill"],
        theme: "engineering_context_eng",
        githubUrl: "https://github.com/hanfang/claude-memory-skill",
      },
      {
        name: "context_engineering_agent_skill",
        displayName: "Context Engineering Agent Skill",
        description: "",
        tools: ["list_context_engineering_agent_skill_skills", "get_context_engineering_agent_skill_skill"],
        theme: "engineering_context_eng",
        githubUrl: "https://github.com/muratcankoylan/Agent-Skills-for-Context-Engineering",
      },
      {
        name: "claude_memory_kit",
        displayName: "Claude Memory Kit",
        description: "",
        tools: ["list_claude_memory_kit_skills", "get_claude_memory_kit_skill"],
        theme: "engineering_context_eng",
        githubUrl: "https://github.com/awrshift/claude-memory-kit",
      },
    ],
  },
  {
    slug: "research",
    name: "Research",
    description: "",
    skills: [
      {
        name: "last30days",
        displayName: "Last30Days",
        description: "",
        tools: [],
        theme: "research",
        githubUrl: "https://github.com/mvanhorn/last30days-skill",
      },
      {
        name: "vexor",
        displayName: "Vexor",
        description: "",
        tools: ["list_vexor_skills", "get_vexor_skill"],
        theme: "research",
        githubUrl: "https://github.com/scarletkc/vexor",
      },
      {
        name: "scientific_agent_skills",
        displayName: "Scientific Agent Skills",
        description: "",
        tools: ["list_scientific_agent_skills_skills", "get_scientific_agent_skills_skill"],
        theme: "research",
        githubUrl: "https://github.com/K-Dense-AI/scientific-agent-skills",
      },
      {
        name: "auto_claude_code_research_in_sleep",
        displayName: "Auto Claude Code Research In Sleep",
        description: "",
        tools: ["list_auto_claude_code_research_in_sleep_skills", "get_auto_claude_code_research_in_sleep_skill"],
        theme: "research",
        githubUrl: "https://github.com/wanshuiyin/Auto-claude-code-research-in-sleep",
      },
      {
        name: "materials_simulation_skills",
        displayName: "Materials Simulation Skills",
        description: "",
        tools: ["list_materials_simulation_skills_skills", "get_materials_simulation_skills_skill"],
        theme: "research",
        githubUrl: "https://github.com/HeshamFS/materials-simulation-skills",
      },
    ],
  },
  {
    slug: "career_development",
    name: "Career Development",
    description: "",
    skills: [
      {
        name: "resume_skills",
        displayName: "Resume Skills",
        description: "",
        tools: ["list_resume_skills_skills", "get_resume_skills_skill"],
        theme: "career_development",
        githubUrl: "https://github.com/Paramchoudhary/ResumeSkills",
      },
    ],
  },
  {
    slug: "education",
    name: "Education",
    description: "",
    skills: [
      {
        name: "tutor_skill",
        displayName: "Tutor Skill",
        description: "",
        tools: ["list_tutor_skill_skills", "get_tutor_skill_skill"],
        theme: "education",
        githubUrl: "https://github.com/bevibing/tutor-skills",
      },
    ],
  },
  {
    slug: "official_rootly_skills",
    name: "Official Rootly Skills",
    description: "",
    skills: [
      {
        name: "rootly_mcp_server",
        displayName: "Rootly Mcp Server",
        description: "",
        tools: ["list_rootly_mcp_server_skills", "get_rootly_mcp_server_skill"],
        theme: "official_rootly_skills",
        githubUrl: "https://github.com/Rootly-AI-Labs/rootly-mcp-server",
      },
    ],
  },
  {
    slug: "engineering_ios_development",
    name: "Engineering Ios Development",
    description: "",
    skills: [
      {
        name: "ios_simulator",
        displayName: "Ios Simulator",
        description: "",
        tools: ["list_ios_simulator_skills", "get_ios_simulator_skill"],
        theme: "engineering_ios_development",
        githubUrl: "https://github.com/conorluddy/ios-simulator-skill",
      },
      {
        name: "app_store_preflight",
        displayName: "App Store Preflight",
        description: "",
        tools: ["list_app_store_preflight_skills", "get_app_store_preflight_skill"],
        theme: "engineering_ios_development",
        githubUrl: "https://github.com/truongduy2611/app-store-preflight-skills",
      },
      {
        name: "app_store_connect_cli",
        displayName: "App Store Connect Cli",
        description: "",
        tools: ["list_app_store_connect_cli_skills", "get_app_store_connect_cli_skill"],
        theme: "engineering_ios_development",
        githubUrl: "https://github.com/rorkai/app-store-connect-cli-skills",
      },
    ],
  },
  {
    slug: "official_coderabbitai_skills",
    name: "Official Coderabbitai Skills",
    description: "",
    skills: [
      {
        name: "coderabbitai_skills",
        displayName: "Coderabbitai Skills",
        description: "",
        tools: ["list_coderabbitai_skills_skills", "get_coderabbitai_skills_skill"],
        theme: "official_coderabbitai_skills",
        githubUrl: "https://github.com/coderabbitai/skills",
      },
    ],
  },
  {
    slug: "engineering_dev_tools",
    name: "Engineering Dev Tools",
    description: "",
    skills: [
      {
        name: "playwright_skill",
        displayName: "Playwright Skill",
        description: "",
        tools: ["list_playwright_skill_skills", "get_playwright_skill_skill"],
        theme: "engineering_dev_tools",
        githubUrl: "https://github.com/lackeyjb/playwright-skill",
      },
      {
        name: "platform_design_skills",
        displayName: "Platform Design Skills",
        description: "",
        tools: ["list_platform_design_skills_skills", "get_platform_design_skills_skill"],
        theme: "engineering_dev_tools",
        githubUrl: "https://github.com/ehmo/platform-design-skills",
      },
      {
        name: "dev_tool_agent",
        displayName: "Dev Tool Agent",
        description: "",
        tools: ["list_dev_tool_agent_skills", "get_dev_tool_agent_skill"],
        theme: "engineering_dev_tools",
        githubUrl: "https://github.com/fvadicamo/dev-agent-skills",
      },
    ],
  },
  {
    slug: "engineering_test",
    name: "Engineering Test",
    description: "",
    skills: [
      {
        name: "test_automation",
        displayName: "Test Automation",
        description: "",
        tools: ["list_test_automation_skills", "get_test_automation_skill"],
        theme: "engineering_test",
        githubUrl: "https://github.com/LambdaTest/agent-skills",
      },
    ],
  },
  {
    slug: "engineering_cybersecurity",
    name: "Engineering Cybersecurity",
    description: "",
    skills: [
      {
        name: "agent_scan",
        displayName: "Agent Scan",
        description: "",
        tools: ["list_agent_scan_skills", "get_agent_scan_skill"],
        theme: "engineering_cybersecurity",
        githubUrl: "https://github.com/snyk/agent-scan",
      },
      {
        name: "vibesec_skill",
        displayName: "Vibesec Skill",
        description: "",
        tools: ["list_vibesec_skill_skills", "get_vibesec_skill_skill"],
        theme: "engineering_cybersecurity",
        githubUrl: "https://github.com/BehiSecc/VibeSec-Skill",
      },
    ],
  },
  {
    slug: "personal_health",
    name: "Personal Health",
    description: "",
    skills: [
      {
        name: "wellally_health",
        displayName: "Wellally Health",
        description: "",
        tools: ["list_wellally_health_skills", "get_wellally_health_skill"],
        theme: "personal_health",
        githubUrl: "https://github.com/huifer/WellAlly-health",
      },
      {
        name: "homeassistant",
        displayName: "Homeassistant",
        description: "",
        tools: ["list_homeassistant_skills", "get_homeassistant_skill"],
        theme: "personal_health",
        githubUrl: "https://github.com/komal-SkyNET/claude-skill-homeassistant",
      },
    ],
  },
  {
    slug: "investment",
    name: "Investment",
    description: "",
    skills: [
      {
        name: "claude_ecom",
        displayName: "Claude Ecom",
        description: "",
        tools: ["list_claude_ecom_skills", "get_claude_ecom_skill"],
        theme: "investment",
        githubUrl: "https://github.com/takechanman1228/claude-ecom",
      },
    ],
  },
  {
    slug: "real_estate",
    name: "Real Estate",
    description: "",
    skills: [
      {
        name: "property_management",
        displayName: "Property Management",
        description: "",
        tools: ["list_property_management_skills", "get_property_management_skill"],
        theme: "real_estate",
      },
    ],
  },
];

export function skillByName(name: string): SkillMeta | undefined {
  for (const theme of THEMES) {
    const found = theme.skills.find((s) => s.name === name);
    if (found) return found;
  }
  return undefined;
}

export function themeBySlug(slug: string): Theme | undefined {
  return THEMES.find((t) => t.slug === slug);
}

export function allSkills(): SkillMeta[] {
  return THEMES.flatMap((t) => t.skills);
}
