"""Skill: huggingface."""

from fastmcp import FastMCP
from core.skill_config import get_presentation_hint

mcp = FastMCP("huggingface")


_SKILLS: dict[str, dict] = {
    'how-do-skills-work': {
        "description": 'In practice, skills are self-contained folders that package instructions, scripts, and resources together for an AI agent to use on a specific use case.',
        "guidance": "In practice, skills are self-contained folders that package instructions, scripts, and resources together for an AI agent to use on a specific use case. Each folder includes a `SKILL.md` file with YAML frontmatter (name and description) followed by the guidance your coding agent follows while the skill is active. \n\n> [!TIP]\n> If your agent doesn't support skills, you can use [`agents/AGENTS.md`](agents/AGENTS.md) directly as a fallback.\n\nThe skills in this repository are also available through:\n - Cursor Marketplace (https://cursor.com/marketplace/huggingface)\n - Codex Plugins Directory (https://developers.openai.com/codex/plugins)",
    },
    'installation': {
        "description": 'Hugging Face skills are compatible with Claude Code, Codex, Gemini CLI, and Cursor.',
        "guidance": "Hugging Face skills are compatible with Claude Code, Codex, Gemini CLI, and Cursor.\n\n### Claude Code\n\n1. Register the repository as a plugin marketplace:  \n   \n```\n/plugin marketplace add huggingface/skills\n```\n\n2. To install a skill, run:  \n   \n```\n/plugin install <skill-name>@huggingface/skills\n```\n\nFor example:  \n\n```\n/plugin install hf-cli@huggingface/skills\n```\n\n### Codex\n\n1. Copy or symlink any skills you want to use from this repository's `skills/` directory into one of Codex's standard `.agents/skills` locations (for example, `$REPO_ROOT/.agents/skills` or `$HOME/.agents/skills`) as described in the [Codex Skills guide](https://developers.openai.com/codex/skills/).\n\n2. Once a skill is available in one of those locations, Codex will discover it using the Agent Skills standard and load the `SKILL.md` instructions when it decides to use that skill or when you explicitly invoke it.\n\n3. If your Codex setup still relies on `AGENTS.md`, you can use the generated [`agents/AGENTS.md`](agents/AGENTS.md) file in this repo as a fallback bundle of instructions.\n\n### Gemini CLI\n\n1. This repo includes `gemini-extension.json` to integrate with the Gemini CLI.\n\n2. Install locally:  \n\n```\ngemini extensions install . --consent\n```\n\nor use the GitHub URL:\n\n```\ngemini extensions install https://github.com/huggingface/skills.git --consent\n```\n\n4. See [Gemini CLI extensions docs](https://geminicli.com/docs/extensions/#installing-an-extension) for more help.\n\n### Cursor\n\nThis repository includes Cursor plugin manifests:\n\n- `.cursor-plugin/plugin.json`\n- `.mcp.json` (configured with the Hugging Face MCP server URL)\n\nInstall from repository URL (or local checkout) via the Cursor plugin flow.\n\nFor contributors, regenerate manifests with:\n\n```bash\n./scripts/publish.sh\n```",
    },
    'skills': {
        "description": 'This repository contains a few skills to get you started.',
        "guidance": 'This repository contains a few skills to get you started. You can also contribute your own skills to the repository.\n\n### Available skills\n\n<!-- This table is auto-generated by scripts/generate_agents.py. Do not edit manually. -->\n<!-- BEGIN_SKILLS_TABLE -->\n| Name | Description | Documentation |\n|------|-------------|---------------|\n| `hf-cli` | Execute Hugging Face Hub operations using the hf CLI. Download models/datasets, upload files, manage repos, and run cloud compute jobs. | [SKILL.md](skills/hf-cli/SKILL.md) |\n| `huggingface-best` | Find the best AI model for any task by querying Hugging Face leaderboards and benchmarks. Recommends top models based on task type, hardware constraints, and benchmark scores. | [SKILL.md](skills/huggingface-best/SKILL.md) |\n| `huggingface-community-evals` | Add and manage evaluation results in Hugging Face model cards. Supports extracting eval tables from README content, importing scores from Artificial Analysis API, and running custom evaluations with vLLM/lighteval. | [SKILL.md](skills/huggingface-community-evals/SKILL.md) |\n| `huggingface-datasets` | Explore, query, and extract data from any Hugging Face dataset using the Dataset Viewer REST API and npx tooling. Zero Python dependencies — covers split/config discovery, row pagination, text search, filtering, SQL via parquetlens, and dataset upload via CLI. | [SKILL.md](skills/huggingface-datasets/SKILL.md) |\n| `huggingface-gradio` | Build Gradio web UIs and demos in Python. Use when creating or editing Gradio apps, components, event listeners, layouts, or chatbots. | [SKILL.md](skills/huggingface-gradio/SKILL.md) |\n| `huggingface-llm-trainer` | Train or fine-tune language models using TRL on Hugging Face Jobs infrastructure. Covers SFT, DPO, GRPO and reward modeling training methods, plus GGUF conversion for local deployment. Includes hardware selection, cost estimation, Trackio monitoring, and Hub persistence. | [SKILL.md](skills/huggingface-llm-trainer/SKILL.md) |\n| `huggingface-local-models` | Use to select models to run locally with llama.cpp and GGUF on CPU, Mac Metal, CUDA, or ROCm. Covers finding GGUFs, quant selection, running servers, exact GGUF file lookup, conversion, and OpenAI-compatible local serving. | [SKILL.md](skills/huggingface-local-models/SKILL.md) |\n| `huggingface-paper-publisher` | Publish and manage research papers on Hugging Face Hub. Supports creating paper pages, linking papers to models/datasets, claiming authorship, and generating professional markdown-based research articles. | [SKILL.md](skills/huggingface-paper-publisher/SKILL.md) |\n| `huggingface-papers` | Look up and read Hugging Face paper pages in markdown, and use the papers API for structured metadata like authors, linked models, datasets, Spaces, and media URLs when needed. | [SKILL.md](skills/huggingface-papers/SKILL.md) |\n| `huggingface-tool-builder` | Build reusable scripts for Hugging Face Hub and API workflows. Useful for chaining API calls, enriching Hub metadata, or automating repeated tasks. | [SKILL.md](skills/huggingface-tool-builder/SKILL.md) |\n| `huggingface-trackio` | Track and visualize ML training experiments with Trackio. Log metrics via Python API and retrieve them via CLI. Supports real-time dashboards synced to HF Spaces. | [SKILL.md](skills/huggingface-trackio/SKILL.md) |\n| `huggingface-vision-trainer` | Train and fine-tune object detection models (RTDETRv2, YOLOS, DETR and others) and image classification models (timm and transformers models — MobileNetV3, MobileViT, ResNet, ViT/DINOv3) using Transformers Trainer API on Hugging Face Jobs infrastructure or locally. Includes COCO dataset format support, Albumentations augmentation, mAP/mAR metrics, trackio tracking, hardware selection, and Hub persistence. | [SKILL.md](skills/huggingface-vision-trainer/SKILL.md) |\n| `transformers-js` | Run state-of-the-art machine learning models directly in JavaScript/TypeScript for NLP, computer vision, audio processing, and multimodal tasks. Works in Node.js and browsers with WebGPU/WASM using Hugging Face models. | [SKILL.md](skills/transformers-js/SKILL.md) |\n<!-- END_SKILLS_TABLE -->\n\n### Using skills in your coding agent\n\nOnce a skill is installed, mention it directly while giving your coding agent instructions:\n\n- "Use the HF LLM trainer skill to estimate the GPU memory needed for a 70B model run."\n- "Use the HF model evaluation skill to launch `run_eval_job.py` on the latest checkpoint."\n- "Use the HF dataset creator skill to draft new few-shot classification templates."\n- "Use the HF paper publisher skill to index my arXiv paper and link it to my model."\n\nYour coding agent automatically loads the corresponding `SKILL.md` instructions and helper scripts while it completes the task.\n\n### Contribute or customize a skill\n\n1. Copy one of the existing skill folders (for example, `hf-datasets/`) and rename it.\n2. Update the new folder\'s `SKILL.md` frontmatter:\n   ```markdown\n   ---\n   name: my-skill-name\n   description: Describe what the skill does and when to use it\n   ---\n\n   # Skill Title\n   Guidance + examples + guardrails\n   ```\n3. Add or edit supporting scripts, templates, and documents referenced by your instructions.\n4. Add an entry to `.claude-plugin/marketplace.json` with a concise, human-readable description.\n5. Run:\n   ```bash\n   ./scripts/publish.sh\n   ```\n   to regenerate and validate all generated metadata.\n6. Reinstall or reload the skill bundle in your coding agent so the updated folder is available.\n\n### Marketplace\n\nThe `.claude-plugin/marketplace.json` file lists skills with human-readable descriptions for the plugin marketplace. The CI validates that skill names and paths match between `SKILL.md` files and `marketplace.json`, but descriptions are maintained separately: `SKILL.md` descriptions guide when Claude activates the skill, while marketplace descriptions are written for humans browsing available skills.\n\n### Additional references\n- Browse the latest instructions, scripts, and templates directly at [huggingface/skills](https://github.com/huggingface/skills).\n- Review Hugging Face documentation for the specific libraries or workflows you reference inside each skill.',
    },
}


@mcp.tool()
def list_huggingface_skills() -> dict:
    """List all available huggingface skills."""
    return {k: v["description"] for k, v in _SKILLS.items()}


@mcp.tool()
def get_huggingface_skill(skill_name: str = None) -> dict:
    """Get full guidance for a specific huggingface skill."""
    if not skill_name or str(skill_name).lower() in ["null", "none"]:
        skill_name = "start-here" if "start-here" in _SKILLS else next(iter(_SKILLS))
    skill_data = _SKILLS.get(skill_name, {"error": f"Unknown skill: {skill_name}"})
    try:
        from fastmcp.server.dependencies import get_http_request
        client_id = get_http_request().headers.get("x-client-id")
    except Exception:
        client_id = None
    if not client_id:
        from core.config import get_client_id
        client_id = get_client_id()
    hint = get_presentation_hint('huggingface', client_id=client_id)
    if hint:
        skill_data = {**skill_data, "_presentation_hint": hint}
    return {
        "id": f"{skill_name}@huggingface",
        "skill_name": skill_name,
        "status": skill_data.get("status", "production"),
        "metadata": {
            "folder": 'huggingface',
            "client_id": client_id,
            "source": "community-library"
        },
        "interface": {
            "commands": [f"/{skill_name}"]
        },
        "content": skill_data
    }
